[internal]
exten => 100,1,Dial(PJSIP/100,20)
 same => n,Hangup()

exten => 101,1,Dial(PJSIP/101,20)
 same => n,Hangup()

exten => 200,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => 500,1,Goto(server-menu,s,1)

[server-menu]
exten => s,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Background(beep)
 same => n,WaitExten(10)
 same => n,Playback(vm-goodbye)
 same => n,Hangup()

exten => 1,1,SayUnixTime(,,"kM")
 same => n,Goto(server-menu,s,1)

exten => 4,1,Dial(PJSIP/101,20)
 same => n,Goto(server-menu,s,1)

exten => i,1,Playback(pbx-invalid)
 same => n,Goto(server-menu,s,1)

exten => t,1,Playback(vm-goodbye)
 same => n,Hangup()
